=== Trexy94/Progetto-TecWeb/data/news.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"

	elementFormDefault="qualified" >
	
	<xsd:element name="news" type="Tnews"/>
		
	<xsd:complexType name="Tnews">
		<xsd:sequence maxOccurs="unbounded">
			<xsd:element name="notizia" type="Tnotizia"/>
		</xsd:sequence>
	</xsd:complexType>

	<!-- definizione Tnotizia -->
	<xsd:complexType name="Tnotizia">
		<xsd:sequence>
			<xsd:element name="img" type="xsd:string"/>
      <xsd:element name="alt" type="xsd:string"/>
			<xsd:element name="titolo" type="xsd:string"/> 
			<xsd:element name="datainserimento" type="xsd:string"/>
			<xsd:element name="testocontenuto" type="xsd:string"/>
		</xsd:sequence>
		<xsd:attribute name="id" type="Tid" use="required"/>			
	</xsd:complexType>

	<!-- definisco Tid -->
	<xsd:simpleType name="Tid">
		<xsd:restriction base="xsd:integer">
			<xsd:minInclusive value="1"/>
			<xsd:maxInclusive value="999999"/>
		</xsd:restriction>
	</xsd:simpleType>
</xsd:schema>

=== Trexy94/Progetto-TecWeb/data/news.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="index.xsl"?>
<news xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation=" news.xsd">
  	
	
<notizia id="1"><img>../img/alessandra.jpg</img><alt>Foto della grande atleta Alessandra Prosdocimo</alt><titolo>ALESSANDRA PROSDOCIMO SFIORA IL PODIO EUROPEO</titolo><datainserimento>2016-2-4</datainserimento><testocontenuto>Nell&amp;#39;impegnativa finale del Campionato Europeo di Judo l&amp;#39;atleta veneta &amp;Atilde;&amp;uml; la migliore della nazionale italiana.&#13;
All&amp;#39;appuntamento di Oberwart in Austria, dove si &amp;Atilde;&amp;uml; svolta la finale degli European Judo Championships, l&amp;#39;Italia si &amp;Atilde;&amp;uml; presentata con uno squadrone di venti atleti. La sfida, del resto, era la pi&amp;Atilde;&amp;sup1; importante ed impegnativa dell&amp;#39;anno, visti gli ambiti titoli continentali in palio. A rappresentare le 41 nazioni del vecchio continente, Israele compresa, c&amp;#39;erano infatti ben 396 atleti. Tra gli &amp;amp;quot;azzurri&amp;amp;quot; Alessandra Prosdocimo, gi&amp;Atilde;&amp;nbsp; vincitrice di un titolo europeo un paio d&amp;#39;anni fa e settima nella Ranking List mondiale, si era distinta anche quest&amp;#39;anno nella selettiva Coppa Europa, vincendo il pi&amp;Atilde;&amp;sup1; alto numero di medaglie della nazionale italiana (due primi posti sia in Ungheria che in Romania ed una medaglia di bronzo vinta a Berlino) facendo cos&amp;Atilde;&amp;not; nascere le speranze di un nuovo e possibile risultato positivo. Alessandra non ha infatti deluso, partendo fin dal primo incontro con quella determinazione e voglia di vincere che le sono caratteristiche. Si &amp;Atilde;&amp;uml; cos&amp;Atilde;&amp;not; fatta rapidamente largo tra le impegnative avversarie, arrivando alla fine all&amp;#39;ultimo e decisivo incontro per il podio. Una sfida pi&amp;Atilde;&amp;sup1; che mai combattuta e conclusasi in un primo tempo alla pari, per essere quindi decisa ai tempi supplementari, dall&amp;#39;ostica Aleksandra Samardzic della Bosnia Herzegovina (terza nella Ranking List mondiale) che alla fine ha avuto la meglio.&#13;
Per capire le difficolt&amp;Atilde;&amp;nbsp; della competizione, basti pensare che tutti i rimanenti 19 atleti dell&amp;#39; affollata nazionale italiana sono usciti di gara fin dal primo o secondo incontro, lasciando alla fine la sola Prosdocimo col non facile compito di rappresentare il nostro paese. Con un po&amp;#39; di amaro in bocca per aver solo sfiorato il podio, Alessandra sta per&amp;Atilde;&amp;sup2; gi&amp;Atilde;&amp;nbsp; pensando al prossimo ed ancor pi&amp;Atilde;&amp;sup1; impegnativo appuntamento internazionale che si terr&amp;Atilde;&amp;nbsp; questa volta nella ben pi&amp;Atilde;&amp;sup1; lontana Abu Dhabi. A fine Ottobre negli Emirati Arabi si svolgeranno infatti i Campionati Mondiali di Judo, ai quali lei ha gi&amp;Atilde;&amp;nbsp; partecipato in un paio di precedenti occasioni. Ci auguriamo quindi di vederla nuovamente in forma per raggiungere quei risultati che tanto impegno merita.</testocontenuto></notizia><notizia id="2"><img>../img/team_west_liga.jpg</img><alt>Il nostro fantastico team west liga in posa</alt><titolo>IL TEAM VENETO VINCE LA WEST LIGA</titolo><datainserimento>2016-2-4</datainserimento><testocontenuto>IL TEAM VENETO VINCE LA WEST LIGA&#13;
Innsbruck (AUT), 7 nov 2015 - Una grande Finale di West Liga per il Team Veneto quella disputata in Austria, che porta la nostra squadra sul pi&amp;Atilde;&amp;sup1; alto gradino del podio della competizione.&#13;
Totto &amp;Atilde;&amp;uml; iniziato a San Lorenzo di Sebato (BZ), il 20 giugno scorso, dove a rappresentare il Veneto sono stati convocati Giacomo Pertile (-66kg), Valeriu Mircea (-73kg), Jacopo Zancanaro (-81kg), e Augustin Cozonac (-90kg) accompagnati dal coach Paolo Scagnetto. In quella prima gara il Team Veneto subiva il 4:6 contro il Judozentrum Innsbruck ma vinceva poi 6:3 sul Friuli Venezia Giulia.&#13;
La squadra alla Finale di West LigaNella seconda gara invece, il 10 ottobre a Montebelluna (TV), la squadra convocata era formata da Giacomo Pertile e Silvio De Giacinto (-66kg), Andrea Dal Zennaro (-73kg), Filippo Bergamin (-81kg), Raffaele Bordignon (-90kg) e Luca Villanova (+90kg) accompagnati questa volta dal coach Davide Paro. A Montebelluna il Team Veneto vinceva 9:1 contro lo Swarovski Wattens e 8:2 sugli altoatesini dell&amp;#39;A.C.R.A.S. Bolzano, portando la nostra squadra al secondo posto in classifica con 9 punti, dietro solamente al Judoteam S&amp;Atilde;&amp;frac14;dtirol.&#13;
Nella terza ed ultima tappa, disputata il 7 novembre a Innsbruck (AUT), il Team Veneto &amp;Atilde;&amp;uml; formato dagli atleti Giacomo Pertile e Silvio De Giacinto (-66kg), Mattia Prosdocimo (-73kg), Filippo Bergamin (-81kg), Raffaele Bordignon (-90kg) e Luca Villanova (+90kg) accompagnati dal coach Matteo Boscolo.&#13;
La nostra squadra incontra subito il Judoteam S&amp;Atilde;&amp;frac14;dtirol, prima in classifica provvisoria, vincendo per 3:2 nell&amp;#39;incontro di andata e 5:0 in quello di ritorno, per un totale di 8:2, raggiungendo cos&amp;Atilde;&amp;not; il primo posto in classifica per la disputa della gara di play-off che determiner&amp;Atilde;&amp;nbsp; le finali. Gara di play-off che vede il Team Veneto vittorioso per 10:0 (5:0 sia all&amp;#39;andata che al ritorno) sul Friuli Venezia Giulia e che ci porta a disputare la finalissima contro i padroni di casa del Judozentrum Innsbruck.&#13;
Supportati dalla bandiera veneta e dai sempre presenti Adriano Pizzolon e Piero Pertile, Team Veneto vince per 4:1 sia l&amp;#39;andata che il ritorno, totalizzando un grande 8:2 che fa salire la nostra rappresentativa sul primo gradino del podio: Team Veneto primo in classifica finale, seguito da  Judozentrum Innsbruck, Judoteam S&amp;Atilde;&amp;frac14;dtirol e Friuli Venezia Giulia.&#13;
Il torneo si conclude con una grande festa tra porchetta e birra offerte dall&amp;#39;organizzazione.&#13;
Grande la soddisfazione del C.T. Regionale e del Vicepresidente del Comitato Regionale Veneto.</testocontenuto></notizia><notizia id="3"><img>../img/mondiali_master.jpg</img><alt>Immagine di quattro ragazze sul podio</alt><titolo>TRE VENETE SUL PODIO MONDIALE MASTER</titolo><datainserimento>2016-2-4</datainserimento><testocontenuto>Amsterdam (NLD), 24 sett 2015 - Sette medaglie per le donne italiane ad Amsterdam ed il medagliere femminile del 7&amp;Acirc;&amp;deg; IJF World Veterans Judo Championships colloca l&amp;#39;Italia al settimo posto con un primo, un secondo e cinque terzi posti. Sul gradino pi&amp;Atilde;&amp;sup1; alto del podio &amp;Atilde;&amp;uml; salita la veneta Manuela Tadini, prima nei 52 kg F2; secondo posto invece per Enrica Cattai, medaglia d&amp;#39;argento nei 63 kg F5, e medaglia di bronzo per Monica Stragliotto nei 70 kg F4.&#13;
Complimenti!</testocontenuto></notizia><notizia id="4"><img>../img/qualifiche.jpg</img><alt>Immagine delle qualifiche</alt><titolo>QUALIFICAZIONI ESORDIENTI-B E ASSOLUTI</titolo><datainserimento>2016-2-4</datainserimento><testocontenuto>Montebelluna (TV), 22 nov 2015 - Si sono svolte oggi al PalaMazzalovo di Montebelluna le fasi di qualificazione per i Campionati Italiani maschili e femminili delle classi Esordienti-B e Assoluti. Molti i judoka veneti che si sono giocati sul tatami l&amp;#39;accesso alle agognate finali, ma solo per alcuni di loro si sono aperte le porte di Ostia (per gli Esordienti) e di Torino (per gli Assoluti) il prossimo dicembre.</testocontenuto></notizia></news>
