=== Trexy94/Progetto-TecWeb/data/utenti.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	elementFormDefault="qualified" >
	
	<xsd:element name="utenti" type="Tutenti" />
	
	<!-- definizione Tutenti -->
	<xsd:complexType name="Tutenti">
		<xsd:sequence maxOccurs="unbounded">
			<xsd:element name="utente" type="Tutente" />
		</xsd:sequence>
	</xsd:complexType>
	<!-- definizione Tutente -->
	<xsd:complexType name="Tutente">
		<xsd:sequence>
			<xsd:element name="username" type="xsd:string" />
			<xsd:element name="password" type="xsd:string" />
		</xsd:sequence>
	</xsd:complexType>
</xsd:schema>

=== Trexy94/Progetto-TecWeb/data/utenti.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="utenti.xsl"?>
<utenti xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation=" utenti.xsd">
  
<utente><username>scici</username><password>password</password></utente>
  <utente>
    <username>rondei</username>
    <password>password</password>
  </utente><utente><username>admin</username><password>admin</password></utente></utenti>
